services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hoget
    restart: always
    volumes:
      - /home/orkun/data/hogetbot/db:/app/db/:Z
      - /home/orkun/data/hogetbot/.env:/app/.env:Z
    network_mode: "container:gluetun"
    depends_on:
      - gluetun
